### ISSUE TITLE
Haml errors after upgrade to Hanami 0.7.0

### ISSUE THREAD

**Issue by pastuxso** [hanami/utils#113]
Hi, after upgrade to Hanami 0.7.0 we are experiment some issues with haml, e.g.

```
Unexpected error while processing request: undefined method `encode' for Wed, 27 Jan 2016:Date
    shared/bundle/ruby/2.2.0/gems/hanami-utils-0.7.0/lib/hanami/utils/escape.rb:532:in `encode'
    shared/bundle/ruby/2.2.0/gems/hanami-utils-0.7.0/lib/hanami/utils/escape.rb:421:in `html'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:61:in `content'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:43:in `to_s'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `map'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `to_s'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:59:in `content'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:43:in `to_s'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `map'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `to_s'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:59:in `content'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:43:in `to_s'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `map'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `to_s'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:59:in `content'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:43:in `to_s'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `map'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `to_s'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:59:in `content'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_node.rb:43:in `to_s'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `map'
    shared/bundle/ruby/2.2.0/gems/hanami-helpers-0.3.0/lib/hanami/helpers/html_helper/html_builder.rb:324:in `to_s'
    shared/bundle/ruby/2.2.0/gems/haml-4.0.7/lib/haml/buffer.rb:144:in `format_script_false_false_false_false_false_true_false'
    current/apps/web/templates/jobs/summary.html.haml:10:in `block in singleton class'
```

on 

```haml
=  job.start_date
```

Any idea?

**Comment by cllns** [comment]
The issue is that `encode` [doesn't call `.to_s`](https://github.com/hanami/utils/blob/master/lib/hanami/utils/escape.rb#L532) on the input, but [it used to](https://github.com/hanami/utils/commit/9221338890dc9e7361509fbfc03d14bf94616ec1).

I added this test, in `test/escape_test.rb`. It works on `0.5.0`, but fails on `0.6.0`, `0.6.1` and `0.7.0`.
```
it "escapes a Date" do
  result = mod.html(Date.new(2016, 01, 27))
  result.must_equal "2016-01-27"
end
```
If we add this test to codebase, we should also add tests for `DateTime` and `Time`.

**Comment by davydovanton** [comment]
@cllns you're right :+1:
Could you create a PR? If you want I can do it.
